version: '3.9'
services:
  goaccess:
    container_name: GoAccess
    #build:                                    #
    #  context: .                              #
    #  dockerfile: Dockerfile                  # - If you want to build.
    #  args:                                   #
    #      maxmind_license_key: <license-key>  #
    ports:
      - 7889:7889
    volumes:
      - .config:/config
      - .goaccess/logs:/opt/log
    environment:
      - MAXMINDDB_LICENSE_KEY=<license-key>
      - TZ=Europe/Brussels
      - TINI_VERBOSITY=0 # If you want to supress TINI outputs.
    image: niniyas/docker-goaccess:latest # or niniyas/goaccess:latest if you want smaller image (~6mb). [DockerHub](https://hub.docker.com/r/niniyas/goaccess)
