name: Build and Push to Docker Hub

on: 
  workflow_dispatch:
  repository_dispatch:
    types: [Build and Push to Docker Hub]
  push:
    branches:
      - master

jobs:
  build-and-push-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
  
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          version: latest
          driver-opts: image=moby/buildkit:master

      - name: Build and push
        id: docker_build_amd64
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/docker-goaccess:amd64
            ${{ secrets.DOCKER_USER }}/docker-goaccess:amd64_commit-${{ steps.short-sha.outputs.sha }}
          platforms: linux/amd64
          build-args: |
            MAXMIND_LICENSE_KEY=${{ secrets.MAXMIND_LICENSE_KEY }}
            OVERLAY_ARCH=amd64

      - name: Build and push
        id: docker_build_arm64
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/docker-goaccess:arm64
            ${{ secrets.DOCKER_USER }}/docker-goaccess:arm64_commit-${{ steps.short-sha.outputs.sha }}
          platforms: linux/arm64
          build-args: |
            MAXMIND_LICENSE_KEY=${{ secrets.MAXMIND_LICENSE_KEY }}
            OVERLAY_ARCH=aarch64

      - name: Build and push
        id: docker_build_armv7
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/docker-goaccess:armv7
            ${{ secrets.DOCKER_USER }}/docker-goaccess:armv7_commit-${{ steps.short-sha.outputs.sha }}
          platforms: linux/arm/v7
          build-args: |
            MAXMIND_LICENSE_KEY=${{ secrets.MAXMIND_LICENSE_KEY }}
            OVERLAY_ARCH=arm

      - name: Discord Success Notifications
        uses: niniyas/discord-webhook-notify@master
        if: success()
        with:
          severity: info
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          details: "Workflow run has been completed successfully!\n **View Here**: [Docker Hub](https://hub.docker.com/r/niniyas/docker-goaccess)"
          
      - name: Discord Failure Notifications
        uses: niniyas/discord-webhook-notify@master
        if: failure()
        with:
         severity: error
         details: "Workflow run has failed!"
         webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
         
      - name: Discord Cancelled Notifications
        uses: niniyas/discord-webhook-notify@master
        if: cancelled()
        with:
         severity: warn
         details: "Workflow run has been cancelled!"
         webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
         
      - name: Pushover Success Notifications
        uses: niniyas/pushover-notify@master
        if: success()
        with:
          pushoverUser: ${{ secrets.PUSHOVER_USER }}
          pushoverApp: ${{ secrets.PUSHOVER_APP }}
          details: "Workflow run has been completed successfully!\n <b>View Here</b>: <a href='https://hub.docker.com/r/niniyas/docker-goaccess'>Docker Hub</a>"
          
      - name: Pushover Failure Notifications
        uses: niniyas/pushover-notify@master
        if: failure()
        with:
          pushoverUser: ${{ secrets.PUSHOVER_USER }}
          pushoverApp: ${{ secrets.PUSHOVER_APP }}
          priority: 1
          details: "Workflow run has failed!"
         
      - name: Pushover Cancelled Notifications
        uses: niniyas/pushover-notify@master
        if: cancelled()
        with:
          pushoverUser: ${{ secrets.PUSHOVER_USER }}
          pushoverApp: ${{ secrets.PUSHOVER_APP }}
          details: "Workflow run has been cancelled!"
          
      - name: Slack Notifications
        if: ${{ always() }}
        uses: ahmadnassri/action-slack-workflow-notifications@v1
        with:
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}

      - name: Telegram Notifications
        uses: KaMeHb-UA/telegram-ci-notify-action@v5
        if: ${{ always() }}
        with:
          status: ${{ steps.docker_build.outcome }}
          bot-token: ${{ secrets.TG_BOT_TOKEN }}
          chat-id: ${{ secrets.TG_CHAT_ID }}
          container-name: niniyas/docker-goaccess
          container-link: https://hub.docker.com/r/niniyas/docker-goaccess
          skip-is-fail: true
          default-branch: $default-branch
