#!/usr/bin/with-contenv bash

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT
----------------------------------------------------------------------
PUID=${PUID}
PGID=${PGID}
UMASK=${UMASK}
TZ=${TZ}

INCLUDE_ALL_LOGS=${INCLUDE_ALL_LOGS}
----------------------------------------------------------------------
"

if [[ ! "${PUID}" -eq 0 ]] && [[ ! "${PGID}" -eq 0 ]]; then
  echo "Executing usermod..."
  mkdir "/tmp/temphome"
  usermod -d "/tmp/temphome" goaccess
  usermod -o -u "${PUID}" goaccess
  usermod -d "${CONFIG_DIR}" goaccess
  rm -rf "/tmp/temphome"
  groupmod -o -g "${PGID}" goaccess
else
  echo "Running as root is not supported, please fix your PUID and PGID!"
  exit 1
fi

echo "Applying permissions to ${CONFIG_DIR}"
chmod "=rwx" "${CONFIG_DIR}"
chown -R "${PUID}":"${PGID}" "${CONFIG_DIR}"
